Add version tag to circuit workflow.

diff --git a/.github/workflows/build-circuits.yml b/.github/workflows/build-circuits.yml
--- a/.github/workflows/build-circuits.yml
+++ b/.github/workflows/build-circuits.yml
@@ -2,14 +2,12 @@ name: Build Circuits
 
 on:
   push:
-    branches:
-      - main
     tags:
-      - "v*.*.*"
+      - "circom_circuits-v*.*.*"
   workflow_dispatch:
     inputs:
       version:
-        description: "Version to release. Must follow the format of 'vX.Y.Z'."
+        description: "Version to release. Must follow the format of 'circom_circuits-vX.Y.Z'."
         required: true
   pull_request: # For testing purposes
 
@@ -25,15 +23,18 @@ jobs:
         env:
           # Use the tag name if it is available, otherwise use the input version.
           # If neither is available, default to the commit hash.
-          VERSION: ${{ github.event.release.tag_name || inputs.version }}
+          VERSION: ${{ github.event.release.tag_name || inputs.version || 'circom_circuits-v0.0.0' }}
         run: |
           if [ -z "$VERSION" ]; then
-            echo "No version tag found. Defaulting to commit hash."
-            VERSION=$GITHUB_SHA
-          elif [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "VERSION must follow the format of 'vX.Y.Z'. Value: '$VERSION'."
+            echo "Could not determine version."
             exit 1
+          elif [[ ! "$VERSION" =~ ^circom_circuits-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "VERSION must follow the format of 'circom_circuits-vX.Y.Z'. Value: '$VERSION'."
+            exit 2
           fi
+
+          # Parse Version: Take only the vX.Y.Z part.
+          VERSION=$(echo $VERSION | cut -d'-' -f2)
 
           # Export the version to be used in the following jobs.
           echo "version=$VERSION" >> $GITHUB_OUTPUT
@@ -99,7 +100,7 @@ jobs:
         working-directory: repo
         env:
           BINARY_NAME: prover
-          BUNDLE_NAME: prover-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           RAPIDSNARK_DIR: circom_circuits/rapidsnark/package
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/${BINARY_NAME}"
@@ -113,7 +114,7 @@ jobs:
         working-directory: repo
         env:
           BINARY_NAME: verifier
-          BUNDLE_NAME: verifier-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           RAPIDSNARK_DIR: circom_circuits/rapidsnark/package
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/${BINARY_NAME}"
@@ -126,7 +127,7 @@ jobs:
       - name: Bundle Pol Witness Generator
         working-directory: repo
         env:
-          BUNDLE_NAME: pol-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           WITNESS_GENERATOR_DIR: circom_circuits/Mantle/pol_cpp
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/witness-generator"
@@ -139,20 +140,20 @@ jobs:
       - name: Upload Rapidsnark Prover
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: prover-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/prover-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
       - name: Upload Rapidsnark Verifier
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: verifier-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/verifier-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
       - name: Upload Pol Witness Generator
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: pol-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/pol-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
   build-windows:
     name: Build Windows Binaries (Native)
@@ -267,7 +268,7 @@ jobs:
         working-directory: repo
         env:
           BINARY_NAME: prover
-          BUNDLE_NAME: prover-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           RAPIDSNARK_DIR: circom_circuits/rapidsnark/package
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/${BINARY_NAME}"
@@ -286,7 +287,7 @@ jobs:
         working-directory: repo
         env:
           BINARY_NAME: verifier
-          BUNDLE_NAME: verifier-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           RAPIDSNARK_DIR: circom_circuits/rapidsnark/package
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/${BINARY_NAME}"
@@ -304,7 +305,7 @@ jobs:
         shell: msys2 {0}
         working-directory: repo
         env:
-          BUNDLE_NAME: pol-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           WITNESS_GENERATOR_DIR: circom_circuits/Mantle/pol_cpp
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/witness-generator"
@@ -322,20 +323,20 @@ jobs:
       - name: Upload Rapidsnark Prover
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: prover-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/prover-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
       - name: Upload Rapidsnark Verifier
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: verifier-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/verifier-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
       - name: Upload Pol Witness Generator
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: pol-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/pol-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
   build-macos:
     name: Build MacOS Binaries (Native)
@@ -405,7 +406,7 @@ jobs:
         working-directory: repo
         env:
           BINARY_NAME: prover
-          BUNDLE_NAME: prover-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           RAPIDSNARK_DIR: circom_circuits/rapidsnark/package_macos_arm64
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/${BINARY_NAME}"
@@ -419,7 +420,7 @@ jobs:
         working-directory: repo
         env:
           BINARY_NAME: verifier
-          BUNDLE_NAME: verifier-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           RAPIDSNARK_DIR: circom_circuits/rapidsnark/package_macos_arm64
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/${BINARY_NAME}"
@@ -432,7 +433,7 @@ jobs:
       - name: Bundle Pol Witness Generator
         working-directory: repo
         env:
-          BUNDLE_NAME: pol-${{ env.OS }}-${{ env.ARCH }}
+          BUNDLE_NAME: pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}
           WITNESS_GENERATOR_DIR: circom_circuits/Mantle/pol_cpp
         run: |
           BUNDLE_DIR="${BUNDLE_NAME}/witness-generator"
@@ -445,20 +446,20 @@ jobs:
       - name: Upload Rapidsnark Prover
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: prover-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/prover-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/prover-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
       - name: Upload Rapidsnark Verifier
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: verifier-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/verifier-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/verifier-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
       - name: Upload Pol Witness Generator
         uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8 
         with:
-          name: pol-${{ env.OS }}-${{ env.ARCH }}.tar.gz
-          path: repo/pol-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          name: pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
+          path: repo/pol-${{ env.VERSION }}-${{ env.OS }}-${{ env.ARCH }}.tar.gz
 
   publish-release:
     name: Create Release
@@ -520,7 +521,7 @@ jobs:
     env:
       VERSION: ${{ needs.setup.outputs.version }}
       UPLOAD_URL: ${{ needs.publish-release.outputs.upload_url }}
-      ARTIFACT_NAME: ${{ matrix.artifact }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
+      ARTIFACT_NAME: ${{ matrix.artifact }}-${{ env.VERSION }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz
     steps:
       - name: Download Artifacts
         uses: actions/download-artifact@448e3f862ab3ef47aa50ff917776823c9946035b
